# Generated by Django 5.2 on 2025-04-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0004_alter_doctor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
