# Generated by Django 5.2 on 2025-04-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0006_doctor_bio_doctor_city_doctor_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FLtoDjango.consultationtype'),
        ),
    ]
