# Generated by Django 5.2 on 2025-04-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0007_doctor_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
