# Generated by Django 5.2 on 2025-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0008_remove_timeslot_time_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
