# Generated by Django 5.2 on 2025-04-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0009_doctor_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='is_active',
            new_name='active',
        ),
    ]
