# Generated by Django 5.2 on 2025-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0011_userbooking_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
