# Generated by Django 5.2 on 2025-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0013_alter_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbooking',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userbooking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
