# Generated by Django 5.2 on 2025-04-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0014_userbooking_age_userbooking_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
