# Generated by Django 5.2 on 2025-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0015_alter_userbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
