# Generated by Django 5.2 on 2025-04-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FLtoDjango', '0017_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_phone',
        ),
    ]
